language: java
before_install:
- openssl aes-256-cbc -K $encrypted_cd9b96c723a5_key -iv $encrypted_cd9b96c723a5_iv -in emulator.json.enc -out emulator.json -d

install: true

jdk:
  - oraclejdk8
cache:
  directories:
    - '$HOME/.m2/repository'
